//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrongholdClient.FileStronghold {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DirectoryListing", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DirectoryListing : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private bool IsDirectoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StrongholdClient.FileStronghold.DirectoryListing[] SubDirectoriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public bool IsDirectory {
            get {
                return this.IsDirectoryField;
            }
            set {
                if ((this.IsDirectoryField.Equals(value) != true)) {
                    this.IsDirectoryField = value;
                    this.RaisePropertyChanged("IsDirectory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public StrongholdClient.FileStronghold.DirectoryListing[] SubDirectories {
            get {
                return this.SubDirectoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.SubDirectoriesField, value) != true)) {
                    this.SubDirectoriesField = value;
                    this.RaisePropertyChanged("SubDirectories");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileStronghold.StrongholdSoap")]
    public interface StrongholdSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownloadFile", ReplyAction="*")]
        StrongholdClient.FileStronghold.DownloadFileResponse DownloadFile(StrongholdClient.FileStronghold.DownloadFileRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFile", ReplyAction="*")]
        StrongholdClient.FileStronghold.UploadFileResponse UploadFile(StrongholdClient.FileStronghold.UploadFileRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewFolder", ReplyAction="*")]
        StrongholdClient.FileStronghold.NewFolderResponse NewFolder(StrongholdClient.FileStronghold.NewFolderRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteItem", ReplyAction="*")]
        StrongholdClient.FileStronghold.DeleteItemResponse DeleteItem(StrongholdClient.FileStronghold.DeleteItemRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDirectoryListing", ReplyAction="*")]
        StrongholdClient.FileStronghold.GetDirectoryListingResponse GetDirectoryListing(StrongholdClient.FileStronghold.GetDirectoryListingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadFile", Namespace="http://tempuri.org/", Order=0)]
        public StrongholdClient.FileStronghold.DownloadFileRequestBody Body;
        
        public DownloadFileRequest() {
        }
        
        public DownloadFileRequest(StrongholdClient.FileStronghold.DownloadFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownloadFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string path;
        
        public DownloadFileRequestBody() {
        }
        
        public DownloadFileRequestBody(string username, string path) {
            this.username = username;
            this.path = path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public StrongholdClient.FileStronghold.DownloadFileResponseBody Body;
        
        public DownloadFileResponse() {
        }
        
        public DownloadFileResponse(StrongholdClient.FileStronghold.DownloadFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownloadFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] DownloadFileResult;
        
        public DownloadFileResponseBody() {
        }
        
        public DownloadFileResponseBody(byte[] DownloadFileResult) {
            this.DownloadFileResult = DownloadFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFile", Namespace="http://tempuri.org/", Order=0)]
        public StrongholdClient.FileStronghold.UploadFileRequestBody Body;
        
        public UploadFileRequest() {
        }
        
        public UploadFileRequest(StrongholdClient.FileStronghold.UploadFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string path;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] data;
        
        public UploadFileRequestBody() {
        }
        
        public UploadFileRequestBody(string username, string path, byte[] data) {
            this.username = username;
            this.path = path;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public StrongholdClient.FileStronghold.UploadFileResponseBody Body;
        
        public UploadFileResponse() {
        }
        
        public UploadFileResponse(StrongholdClient.FileStronghold.UploadFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UploadFileResult;
        
        public UploadFileResponseBody() {
        }
        
        public UploadFileResponseBody(int UploadFileResult) {
            this.UploadFileResult = UploadFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewFolderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewFolder", Namespace="http://tempuri.org/", Order=0)]
        public StrongholdClient.FileStronghold.NewFolderRequestBody Body;
        
        public NewFolderRequest() {
        }
        
        public NewFolderRequest(StrongholdClient.FileStronghold.NewFolderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewFolderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string path;
        
        public NewFolderRequestBody() {
        }
        
        public NewFolderRequestBody(string username, string path) {
            this.username = username;
            this.path = path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewFolderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewFolderResponse", Namespace="http://tempuri.org/", Order=0)]
        public StrongholdClient.FileStronghold.NewFolderResponseBody Body;
        
        public NewFolderResponse() {
        }
        
        public NewFolderResponse(StrongholdClient.FileStronghold.NewFolderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class NewFolderResponseBody {
        
        public NewFolderResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteItem", Namespace="http://tempuri.org/", Order=0)]
        public StrongholdClient.FileStronghold.DeleteItemRequestBody Body;
        
        public DeleteItemRequest() {
        }
        
        public DeleteItemRequest(StrongholdClient.FileStronghold.DeleteItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string path;
        
        public DeleteItemRequestBody() {
        }
        
        public DeleteItemRequestBody(string username, string path) {
            this.username = username;
            this.path = path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteItemResponse", Namespace="http://tempuri.org/", Order=0)]
        public StrongholdClient.FileStronghold.DeleteItemResponseBody Body;
        
        public DeleteItemResponse() {
        }
        
        public DeleteItemResponse(StrongholdClient.FileStronghold.DeleteItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteItemResponseBody {
        
        public DeleteItemResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDirectoryListingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDirectoryListing", Namespace="http://tempuri.org/", Order=0)]
        public StrongholdClient.FileStronghold.GetDirectoryListingRequestBody Body;
        
        public GetDirectoryListingRequest() {
        }
        
        public GetDirectoryListingRequest(StrongholdClient.FileStronghold.GetDirectoryListingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDirectoryListingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        public GetDirectoryListingRequestBody() {
        }
        
        public GetDirectoryListingRequestBody(string userName) {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDirectoryListingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDirectoryListingResponse", Namespace="http://tempuri.org/", Order=0)]
        public StrongholdClient.FileStronghold.GetDirectoryListingResponseBody Body;
        
        public GetDirectoryListingResponse() {
        }
        
        public GetDirectoryListingResponse(StrongholdClient.FileStronghold.GetDirectoryListingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDirectoryListingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StrongholdClient.FileStronghold.DirectoryListing GetDirectoryListingResult;
        
        public GetDirectoryListingResponseBody() {
        }
        
        public GetDirectoryListingResponseBody(StrongholdClient.FileStronghold.DirectoryListing GetDirectoryListingResult) {
            this.GetDirectoryListingResult = GetDirectoryListingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StrongholdSoapChannel : StrongholdClient.FileStronghold.StrongholdSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StrongholdSoapClient : System.ServiceModel.ClientBase<StrongholdClient.FileStronghold.StrongholdSoap>, StrongholdClient.FileStronghold.StrongholdSoap {
        
        public StrongholdSoapClient() {
        }
        
        public StrongholdSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StrongholdSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StrongholdSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StrongholdSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StrongholdClient.FileStronghold.DownloadFileResponse StrongholdClient.FileStronghold.StrongholdSoap.DownloadFile(StrongholdClient.FileStronghold.DownloadFileRequest request) {
            return base.Channel.DownloadFile(request);
        }
        
        public byte[] DownloadFile(string username, string path) {
            StrongholdClient.FileStronghold.DownloadFileRequest inValue = new StrongholdClient.FileStronghold.DownloadFileRequest();
            inValue.Body = new StrongholdClient.FileStronghold.DownloadFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.path = path;
            StrongholdClient.FileStronghold.DownloadFileResponse retVal = ((StrongholdClient.FileStronghold.StrongholdSoap)(this)).DownloadFile(inValue);
            return retVal.Body.DownloadFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StrongholdClient.FileStronghold.UploadFileResponse StrongholdClient.FileStronghold.StrongholdSoap.UploadFile(StrongholdClient.FileStronghold.UploadFileRequest request) {
            return base.Channel.UploadFile(request);
        }
        
        public int UploadFile(string username, string path, byte[] data) {
            StrongholdClient.FileStronghold.UploadFileRequest inValue = new StrongholdClient.FileStronghold.UploadFileRequest();
            inValue.Body = new StrongholdClient.FileStronghold.UploadFileRequestBody();
            inValue.Body.username = username;
            inValue.Body.path = path;
            inValue.Body.data = data;
            StrongholdClient.FileStronghold.UploadFileResponse retVal = ((StrongholdClient.FileStronghold.StrongholdSoap)(this)).UploadFile(inValue);
            return retVal.Body.UploadFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StrongholdClient.FileStronghold.NewFolderResponse StrongholdClient.FileStronghold.StrongholdSoap.NewFolder(StrongholdClient.FileStronghold.NewFolderRequest request) {
            return base.Channel.NewFolder(request);
        }
        
        public void NewFolder(string username, string path) {
            StrongholdClient.FileStronghold.NewFolderRequest inValue = new StrongholdClient.FileStronghold.NewFolderRequest();
            inValue.Body = new StrongholdClient.FileStronghold.NewFolderRequestBody();
            inValue.Body.username = username;
            inValue.Body.path = path;
            StrongholdClient.FileStronghold.NewFolderResponse retVal = ((StrongholdClient.FileStronghold.StrongholdSoap)(this)).NewFolder(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StrongholdClient.FileStronghold.DeleteItemResponse StrongholdClient.FileStronghold.StrongholdSoap.DeleteItem(StrongholdClient.FileStronghold.DeleteItemRequest request) {
            return base.Channel.DeleteItem(request);
        }
        
        public void DeleteItem(string username, string path) {
            StrongholdClient.FileStronghold.DeleteItemRequest inValue = new StrongholdClient.FileStronghold.DeleteItemRequest();
            inValue.Body = new StrongholdClient.FileStronghold.DeleteItemRequestBody();
            inValue.Body.username = username;
            inValue.Body.path = path;
            StrongholdClient.FileStronghold.DeleteItemResponse retVal = ((StrongholdClient.FileStronghold.StrongholdSoap)(this)).DeleteItem(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StrongholdClient.FileStronghold.GetDirectoryListingResponse StrongholdClient.FileStronghold.StrongholdSoap.GetDirectoryListing(StrongholdClient.FileStronghold.GetDirectoryListingRequest request) {
            return base.Channel.GetDirectoryListing(request);
        }
        
        public StrongholdClient.FileStronghold.DirectoryListing GetDirectoryListing(string userName) {
            StrongholdClient.FileStronghold.GetDirectoryListingRequest inValue = new StrongholdClient.FileStronghold.GetDirectoryListingRequest();
            inValue.Body = new StrongholdClient.FileStronghold.GetDirectoryListingRequestBody();
            inValue.Body.userName = userName;
            StrongholdClient.FileStronghold.GetDirectoryListingResponse retVal = ((StrongholdClient.FileStronghold.StrongholdSoap)(this)).GetDirectoryListing(inValue);
            return retVal.Body.GetDirectoryListingResult;
        }
    }
}
